### ISSUE TITLE
Need help to install on odoo comunity 10

### ISSUE THREAD

**Issue by 360org** [OCA/knowledge#114]
Hello OCA!
i need little help to install module
i try to install like app on odoo app but when i try to update the list it didn't show up plz help how can i install this module ?

**Comment by pedrobaeza** [comment]
These modules are not yet migrated to v10.

**Comment by 360org** [comment]
Hello so when the knowledge release for v10? also im interested about OCA/stock-logistics-\* modules show when it release? anyway to test with these module?

**Comment by pedrobaeza** [comment]
When someone migrates them. This is something voluntary.

**Comment by eugen-don** [comment]
hi i have migrated the most part of document management to v 10... but im stuck at the module document_url... i will be trying to contribute the ported modules in the next few days.

**Comment by 360org** [comment]
nice thanks @eugen-don so all of them up to date on github?

**Comment by lasley** [comment]
@W360S - you can follow v10 migration effort by using the dedicated ticket in each repo. This repo's is #105

**Comment by max3903** [comment]
@eugen-don Can you comment this issue #105 to let us know which module you migrated and their pull request? Thank you.

**Comment by max3903** [comment]
@W360S if you want a date, I suggest you sponsor/hire a community member/developer to migrate the one you want.

**Comment by lasley** [comment]
@max3903 - Any reason this was reopened? I don't see any action items here other than the need to hire an integrator, which I do not believe should happen via GH ticket.

**Comment by eugen-don** [comment]
hi i found another pr with nearly complete migration of repo knowledge https://github.com/OCA/knowledge/pull/111

since mine isnt as complete as this one, i suggest using the code in the pr. The module is installable (probably i didnt test, mine is though) but as i can tell the mail sending method in document_page_approval wont work. 

@max3903 In my own migration im stuck at the javascript part... sry for the wait
