### ISSUE TITLE
[9.0] TravisCI Transifex build failing

### ISSUE THREAD

**Issue by dreispt** [OCA/knowledge#81]
See https://travis-ci.org/OCA/knowledge/jobs/95794475#L213 :

```
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
```

**Comment by max3903** [comment]
@Ehtaga Can you look into this please ? Project is created on Transifex but there is no resources:
https://www.transifex.com/oca/OCA-knowledge-9-0/content/

**Comment by Ehtaga** [comment]
Transifex export script only works for versions 7.0 and 8.0.
The Odoo connexion classes have only be implemented for those 2 versions.
Take a look at https://github.com/OCA/maintainer-quality-tools/blob/master/travis/odoo_connection.py

I didn't have time yet to look into version 9.0, maybe it can use the same connexion process as 8.0, so you just need to set the context_mapping:

```
context_mapping = {
    "7.0": Odoo7Context,
    "8.0": Odoo8Context,
    "9.0": Odoo8Context,
}
```

Otherwise an Odoo9Context subclass has to be implemented.

**Comment by pedrobaeza** [comment]
Let's continue this discussion on the general issue in https://github.com/OCA/maintainer-quality-tools/issues/285
